[package]
name = "asynccoffee"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = "1.8.0"
env_logger = "0.10.0"
log = "0.4.17"
rand = "0.8.5"
rand_distr = "0.4.3"
tokio = { version = "1.23.0", features = ["full"] }
